### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by xiaoiker** [rulixiang/segformer-pytorch#1]
Hi, I am really like this kind of pure and clean code. Thanks a lot.

I'd like to ask how about the performance compared to original one?

Many thanks.

**Comment by rulixiang** [comment]
Hey, I'm glad you like this code. 
I tested this implementation on the `PASCAL VOC 2012 dataset`. It achieved the same performance as the official implementation.
You can compare the training log of the [official implementation](https://github.com/rulixiang/segformer-pytorch/blob/main/20210709_161618.log) and [this implementation](https://github.com/rulixiang/segformer-pytorch/blob/main/test.log).
