### ISSUE TITLE
请问有训练好的模型吗？

### ISSUE THREAD

**Issue by durui-12315** [rulixiang/segformer-pytorch#5]

**Comment by rulixiang** [comment]
你好，我没有找到之前实验的模型文件；所以你可能需要自己运行一次。

**Comment by durui-12315** [comment]
感谢回复，已翻墙下载了预训练模型。



在 2022-04-24 10:46:43，"Lixiang Ru" ***@***.***> 写道：

你好，我没有找到之前实验的模型文件；所以你可能需要自己运行一次。
